title: AVoidX - An Augmented VR Game
description: Blending the real and the virtual through real-time volumetric capture
show_downloads: true
theme: jekyll-theme-slate

github:
  repository_url: https://youtu.be/jt9EFqwH3Zg
  zip_url: https://vcl3d.github.io/AVoidX/
  owner_url: https://vcl3d.github.io
  owner_name: VCL3D
