//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public static class MathUtils
{
	public static float eps = 1e-5f;

	public static float Sign(float u)
	{
		if (Mathf.Abs(u) < eps)
			return 0;
		return Mathf.Sign (u);
	}
}


